// Workspace — ZATCA-style Phase 1 QR helper.
// Pure-V2 module. Does NOT import lib/zatca-engine.
//
// Builds a TLV (tag-length-value) byte string with the 5 Phase 1 tags:
//   1. Seller name           (UTF-8)
//   2. VAT registration no.  (UTF-8)
//   3. Invoice timestamp     (ISO 8601 UTC)
//   4. Invoice total         (string with VAT, e.g. "115.00")
//   5. VAT amount            (string, e.g. "15.00")
//
// Returns the base64 string AND a real QR image (data URL) generated by the
// `qrcode` package that is already a project dependency.
//
// Phase 2 fields (XML hash, digital signature, public key, cryptographic
// stamp, signed properties) are NOT generated in this candidate; that
// requires server-side signing infrastructure — recorded as a blocker.

import QRCode from "qrcode";

import { tlvBytesPhase1, phase1TlvUint8ArrayToBase64, normalizePhase1Money } from "@/lib/workspace/exports/zatca-phase1-tlv";

export type ZatcaPhase1Input = {
  sellerName: string;
  vatNumber: string;
  // ISO 8601 timestamp; default = now in UTC.
  timestamp?: string;
  // Numeric values; serialized to strings with 2 decimals.
  invoiceTotal: number;
  vatAmount: number;
};

export type ZatcaPhase1Result = {
  base64: string;
  payloadHex: string;
  imageDataUrl: string;
  fields: {
    sellerName: string;
    vatNumber: string;
    timestamp: string;
    invoiceTotal: string;
    vatAmount: string;
  };
};

function bytesToHex(bytes: Uint8Array): string {
  return Array.from(bytes)
    .map((byte) => byte.toString(16).padStart(2, "0"))
    .join("");
}

/**
 * Build the full Phase 1 TLV payload as a base64 string + the rendered QR
 * image as a data URL. Suitable for direct use in <img src=...> and for
 * embedding into a PDF.
 */
export async function buildPhase1Qr(
  input: ZatcaPhase1Input,
): Promise<ZatcaPhase1Result> {
  const sellerName = input.sellerName.trim();
  const vatNumber = input.vatNumber.trim();
  const timestamp =
    input.timestamp ??
    new Date().toISOString().replace(/\.\d{3}Z$/, "Z");
  const invoiceTotal = normalizePhase1Money(input.invoiceTotal);
  const vatAmount = normalizePhase1Money(input.vatAmount);

  const payload = tlvBytesPhase1({
    sellerName,
    vatNumber,
    timestampIso: timestamp,
    invoiceTotal,
    vatAmount,
  });

  const base64 = phase1TlvUint8ArrayToBase64(payload);
  const payloadHex = bytesToHex(payload);

  // QR encoding: medium error correction is sufficient for a 5-tag Phase 1
  // payload; data URL output is portable across <img>, canvas, and pdf-lib.
  const imageDataUrl = await QRCode.toDataURL(base64, {
    errorCorrectionLevel: "M",
    margin: 1,
    width: 256,
    color: { dark: "#0B0B0B", light: "#FFFFFF" },
  });

  return {
    base64,
    payloadHex,
    imageDataUrl,
    fields: {
      sellerName,
      vatNumber,
      timestamp,
      invoiceTotal,
      vatAmount,
    },
  };
}
