// Workspace V2 — ZATCA-style Phase 1 QR helper.
// Pure-V2 module. Does NOT import lib/zatca-engine.
//
// Builds a TLV (tag-length-value) byte string with the 5 Phase 1 tags:
//   1. Seller name           (UTF-8)
//   2. VAT registration no.  (UTF-8)
//   3. Invoice timestamp     (ISO 8601 UTC)
//   4. Invoice total         (string with VAT, e.g. "115.00")
//   5. VAT amount            (string, e.g. "15.00")
//
// Returns the base64 string AND a real QR image (data URL) generated by the
// `qrcode` package that is already a project dependency.
//
// Phase 2 fields (XML hash, digital signature, public key, cryptographic
// stamp, signed properties) are NOT generated in this candidate; that
// requires server-side signing infrastructure — recorded as a blocker.

import QRCode from "qrcode";

export type ZatcaPhase1Input = {
  sellerName: string;
  vatNumber: string;
  // ISO 8601 timestamp; default = now in UTC.
  timestamp?: string;
  // Numeric values; serialized to strings with 2 decimals.
  invoiceTotal: number;
  vatAmount: number;
};

export type ZatcaPhase1Result = {
  base64: string;
  payloadHex: string;
  imageDataUrl: string;
  fields: {
    sellerName: string;
    vatNumber: string;
    timestamp: string;
    invoiceTotal: string;
    vatAmount: string;
  };
};

/**
 * Encode a single TLV chunk: tag (1 byte) | length (1 byte) | UTF-8 value bytes.
 * Throws if value > 255 bytes (Phase 1 spec) — rare for the 5 tags above.
 */
function tlv(tag: number, value: string): Uint8Array {
  const bytes = new TextEncoder().encode(value);
  if (bytes.length > 255) {
    throw new Error(
      `ZATCA TLV tag ${tag} exceeds 255 bytes (got ${bytes.length})`,
    );
  }
  const out = new Uint8Array(bytes.length + 2);
  out[0] = tag;
  out[1] = bytes.length;
  out.set(bytes, 2);
  return out;
}

function concatBytes(parts: Uint8Array[]): Uint8Array {
  const total = parts.reduce((sum, part) => sum + part.length, 0);
  const out = new Uint8Array(total);
  let offset = 0;
  for (const part of parts) {
    out.set(part, offset);
    offset += part.length;
  }
  return out;
}

function bytesToBase64(bytes: Uint8Array): string {
  // Browser path: btoa on a binary string built char-by-char.
  if (typeof btoa === "function") {
    let binary = "";
    for (let i = 0; i < bytes.length; i++) {
      binary += String.fromCharCode(bytes[i]);
    }
    return btoa(binary);
  }
  // Node fallback (used by SSR or tests).
  // eslint-disable-next-line @typescript-eslint/no-require-imports
  const Buffer = (globalThis as { Buffer?: { from: (b: Uint8Array) => { toString: (e: string) => string } } }).Buffer;
  if (Buffer) return Buffer.from(bytes).toString("base64");
  throw new Error("No base64 encoder available");
}

function bytesToHex(bytes: Uint8Array): string {
  return Array.from(bytes)
    .map((byte) => byte.toString(16).padStart(2, "0"))
    .join("");
}

function formatMoney(value: number): string {
  if (!Number.isFinite(value)) return "0.00";
  return value.toFixed(2);
}

/**
 * Build the full Phase 1 TLV payload as a base64 string + the rendered QR
 * image as a data URL. Suitable for direct use in <img src=...> and for
 * embedding into a PDF.
 */
export async function buildPhase1Qr(
  input: ZatcaPhase1Input,
): Promise<ZatcaPhase1Result> {
  const sellerName = input.sellerName.trim();
  const vatNumber = input.vatNumber.trim();
  const timestamp =
    input.timestamp ??
    new Date().toISOString().replace(/\.\d{3}Z$/, "Z");
  const invoiceTotal = formatMoney(input.invoiceTotal);
  const vatAmount = formatMoney(input.vatAmount);

  const payload = concatBytes([
    tlv(1, sellerName),
    tlv(2, vatNumber),
    tlv(3, timestamp),
    tlv(4, invoiceTotal),
    tlv(5, vatAmount),
  ]);

  const base64 = bytesToBase64(payload);
  const payloadHex = bytesToHex(payload);

  // QR encoding: medium error correction is sufficient for a 5-tag Phase 1
  // payload; data URL output is portable across <img>, canvas, and pdf-lib.
  const imageDataUrl = await QRCode.toDataURL(base64, {
    errorCorrectionLevel: "M",
    margin: 1,
    width: 256,
    color: { dark: "#0B0B0B", light: "#FFFFFF" },
  });

  return {
    base64,
    payloadHex,
    imageDataUrl,
    fields: {
      sellerName,
      vatNumber,
      timestamp,
      invoiceTotal,
      vatAmount,
    },
  };
}
