from __future__ import annotations

import json
import os
import re
import shutil
import subprocess
import sys
import time
from dataclasses import dataclass, asdict, field
from datetime import datetime
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple


# ============================================================
# Gulf Hisab Fixer Engine V1
# ------------------------------------------------------------
# Purpose:
#   - Read QA reports generated by the QA Inspector
#   - Apply SAFE, rule-based fixes automatically
#   - Never touch risky business logic automatically
#   - Generate a fixer execution report
#   - Generate escalation instructions for unresolved issues
#
# SAFE AUTO-FIX SCOPE (V1):
#   - Internal UI label leaks: ZA, VT, WA, RP, IV, MODULE
#   - Placeholder hrefs: #, javascript:void(0)
#   - Empty CTA text in JSX/TSX where obvious replacement is possible
#   - Wrong / old logo references when official filenames are known
#   - Lightweight popover/dropdown Close button removal (pattern-based)
#   - Hide navigation items that point to known 404 / unresolved routes
#   - Simple contrast token replacements if configured
#
# NOT SAFE FOR AUTO-FIX:
#   - accounting logic
#   - VAT/ZATCA logic
#   - migrations/schema changes
#   - permissions/security changes
#   - destructive route rewrites
#   - hidden stateful workflow behavior
# ============================================================


# -----------------------------
# Models
# -----------------------------

@dataclass
class FixAction:
    issue_id: str
    action_type: str
    target_file: Optional[str]
    status: str
    summary: str
    before: Optional[str] = None
    after: Optional[str] = None
    notes: Optional[str] = None


@dataclass
class FixerReport:
    generated_at: str
    project_root: str
    qa_report_path: str
    applied_count: int
    skipped_count: int
    failed_count: int
    actions: List[FixAction] = field(default_factory=list)
    escalations: List[str] = field(default_factory=list)


# -----------------------------
# Helpers
# -----------------------------

def now_iso() -> str:
    return datetime.utcnow().isoformat() + "Z"


def read_text(path: Path) -> str:
    return path.read_text(encoding="utf-8", errors="ignore")


def write_text(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")


def backup_file(path: Path, backup_root: Path) -> Path:
    rel = path.as_posix().replace(":", "")
    backup_path = backup_root / rel
    backup_path.parent.mkdir(parents=True, exist_ok=True)
    shutil.copy2(path, backup_path)
    return backup_path


def save_json(path: Path, payload: Any) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        json.dump(payload, f, indent=2, ensure_ascii=False)


def list_code_files(root: Path, exts: Tuple[str, ...]) -> List[Path]:
    excluded_parts = ("node_modules", ".next", "backend/vendor", "qa_reports", "qa_fixer_backups", ".git", "storage")
    results: List[Path] = []
    for ext in exts:
        results.extend(root.rglob(f"*{ext}"))
    return [p for p in results if p.is_file() and not any(part in p.as_posix() for part in excluded_parts)]


# -----------------------------
# Fixer Engine
# -----------------------------

class GulfHisabFixerEngine:
    def __init__(self, project_root: Path, qa_report_path: Path, config: Dict[str, Any]) -> None:
        self.project_root = project_root
        self.qa_report_path = qa_report_path
        self.config = config
        self.qa_report = self._load_qa_report(qa_report_path)
        self.actions: List[FixAction] = []
        self.escalations: List[str] = []
        self.backup_root = project_root / "qa_fixer_backups" / datetime.utcnow().strftime("%Y%m%d_%H%M%S")
        self.official_full_logo = config.get("official_full_logo", "gulf-hisab-wordmark")
        self.official_icon_logo = config.get("official_icon_logo", "icon")

    def _load_qa_report(self, path: Path) -> Dict[str, Any]:
        return json.loads(read_text(path))

    def run(self) -> FixerReport:
        issues = self._all_issues()

        for issue in issues:
            title = issue.get("title", "")
            category = issue.get("category", "")
            severity = issue.get("severity", "")
            print(f"[Fixer] Evaluating {title or 'untitled issue'}")

            handled = False

            if title == "Internal or placeholder UI labels leaked to production UI":
                handled = self.fix_internal_label_leaks(issue)
            elif title == "Card badge system looks like internal taxonomy, not polished UX":
                handled = self.fix_module_badges(issue)
            elif title == "Placeholder links detected":
                handled = self.fix_placeholder_links(issue)
            elif title == "Empty action element detected":
                handled = self.fix_empty_ctas(issue)
            elif title == "Broken or failing links detected":
                handled = self.fix_known_broken_nav(issue)
            elif category == "ux" and "close" in title.lower():
                handled = self.fix_lightweight_close_buttons(issue)

            if not handled:
                escalation = f"Escalate [{severity.upper()}] {category}: {title}"
                if escalation not in self.escalations:
                    self.escalations.append(escalation)

        self.fix_logo_references()
        self.fix_lightweight_close_buttons_from_config()

        report = FixerReport(
            generated_at=now_iso(),
            project_root=str(self.project_root),
            qa_report_path=str(self.qa_report_path),
            applied_count=sum(1 for a in self.actions if a.status == "applied"),
            skipped_count=sum(1 for a in self.actions if a.status == "skipped"),
            failed_count=sum(1 for a in self.actions if a.status == "failed"),
            actions=self.actions,
            escalations=self.escalations,
        )
        return report

    def _all_issues(self) -> List[Dict[str, Any]]:
        issues: List[Dict[str, Any]] = []
        for check in self.qa_report.get("checks", []):
            issues.extend(check.get("issues", []))
        return issues

    def _find_candidate_files(self) -> List[Path]:
        exts = tuple(self.config.get("search_extensions", [".tsx", ".ts", ".jsx", ".js", ".blade.php", ".php"]))
        return list_code_files(self.project_root, exts)

    def _safe_replace_in_file(self, file_path: Path, replacements: List[Tuple[str, str]], issue_id: str, summary: str,
                              regex: bool = False, count_limit: int = 0) -> bool:
        try:
            if not file_path.exists():
                self.actions.append(FixAction(issue_id, "replace", str(file_path), "skipped", f"File not found: {summary}"))
                return False

            original = read_text(file_path)
            updated = original
            total_changes = 0

            for old, new in replacements:
                if regex:
                    updated, n = re.subn(old, new, updated, count=0 if count_limit == 0 else count_limit, flags=re.MULTILINE)
                else:
                    n = updated.count(old)
                    updated = updated.replace(old, new)
                total_changes += n

            if updated == original:
                self.actions.append(FixAction(issue_id, "replace", str(file_path), "skipped", summary, notes="No matching pattern found"))
                return False

            backup_file(file_path, self.backup_root)
            write_text(file_path, updated)
            self.actions.append(FixAction(issue_id, "replace", str(file_path), "applied", summary, notes=f"Total changes: {total_changes}"))
            return True
        except Exception as e:
            self.actions.append(FixAction(issue_id, "replace", str(file_path), "failed", summary, notes=str(e)))
            return False

    def fix_internal_label_leaks(self, issue: Dict[str, Any]) -> bool:
        issue_id = issue.get("id", "unknown")
        banned_labels = self.config.get("internal_label_replacements", {
            "ZA": "",
            "VT": "",
            "WA": "",
            "RP": "",
            "IV": "",
            "MODULE": "",
            "Module": "",
        })
        changed = False

        for file_path in self._find_candidate_files():
            text = read_text(file_path)
            if not any(label in text for label in banned_labels.keys()):
                continue

            replacements: List[Tuple[str, str]] = []
            for old, new in banned_labels.items():
                # conservative removal only when used as standalone chip-ish label
                replacements.extend([
                    (f">{old}<", f">{new}<"),
                    (f'"{old}"', f'"{new}"'),
                    (f"'{old}'", f"'{new}'"),
                ])
            if self._safe_replace_in_file(file_path, replacements, issue_id, "Remove leaked internal UI labels"):
                changed = True

        return changed

    def fix_module_badges(self, issue: Dict[str, Any]) -> bool:
        issue_id = issue.get("id", "unknown")
        changed = False
        suspicious_patterns = self.config.get("module_badge_patterns", [
            r">\s*MODULE\s*<",
            r">\s*Module\s*<",
            r">\s*ZA\s*<",
            r">\s*VT\s*<",
            r">\s*WA\s*<",
            r">\s*RP\s*<",
            r">\s*IV\s*<",
        ])

        for file_path in self._find_candidate_files():
            text = read_text(file_path)
            if not any(re.search(p, text) for p in suspicious_patterns):
                continue
            replacements = [(pattern, "><") for pattern in suspicious_patterns]
            if self._safe_replace_in_file(file_path, replacements, issue_id, "Remove noisy card badge labels", regex=True):
                changed = True

        return changed

    def fix_placeholder_links(self, issue: Dict[str, Any]) -> bool:
        issue_id = issue.get("id", "unknown")
        changed = False
        for file_path in self._find_candidate_files():
            text = read_text(file_path)
            if 'href="#"' not in text and "javascript:void(0)" not in text:
                continue

            replacements = [
                ('href="#"', 'href="/"'),
                ('href="#"', 'href="/"'),
                ('javascript:void(0)', '/'),
            ]
            if self._safe_replace_in_file(file_path, replacements, issue_id, "Replace placeholder links with safe fallback"):
                changed = True
        return changed

    def fix_empty_ctas(self, issue: Dict[str, Any]) -> bool:
        issue_id = issue.get("id", "unknown")
        changed = False
        cta_patterns = self.config.get("empty_cta_replacements", [
            (r"<button([^>]*)>\s*</button>", r"<button\1>Start Free Trial</button>"),
            (r"<a([^>]*)>\s*</a>", r"<a\1>Learn More</a>"),
        ])
        for file_path in self._find_candidate_files():
            text = read_text(file_path)
            if "<button" not in text and "<a" not in text:
                continue
            if self._safe_replace_in_file(file_path, cta_patterns, issue_id, "Fill obviously empty CTA labels", regex=True):
                changed = True
        return changed

    def fix_known_broken_nav(self, issue: Dict[str, Any]) -> bool:
        issue_id = issue.get("id", "unknown")
        route_map = self.config.get("known_404_nav_labels", [
            "User Workspace",
            "Admin Workspace",
            "Assistant Workspace",
            "Agent Workspace",
        ])
        changed = False

        for file_path in self._find_candidate_files():
            text = read_text(file_path)
            if not any(label in text for label in route_map):
                continue

            updated = text
            for label in route_map:
                updated = re.sub(
                    rf"\{{?\s*label\s*:\s*['\"]{re.escape(label)}['\"].*?\n",
                    "",
                    updated,
                    flags=re.DOTALL,
                )
                updated = updated.replace(f'>{label}<', '></')

            if updated != text:
                backup_file(file_path, self.backup_root)
                write_text(file_path, updated)
                self.actions.append(FixAction(issue_id, "nav_hide", str(file_path), "applied", "Hide likely broken visible workspace tabs"))
                changed = True

        return changed

    def fix_logo_references(self) -> bool:
        changed = False
        issue_id = "logo-standardization"
        legacy_patterns = self.config.get("logo_reference_replacements", [
            ("/logo.svg", f"/{self.official_full_logo}.svg"),
            ("logo.svg", f"{self.official_full_logo}.svg"),
            ("icon-logo.svg", f"{self.official_icon_logo}.svg"),
            ("small-logo.svg", f"{self.official_icon_logo}.svg"),
            ("Gulf Hisab SVG Logo 1", self.official_full_logo),
            ("Gulf Hisabl SVG Logo 2", self.official_icon_logo),
        ])

        for file_path in self._find_candidate_files():
            text = read_text(file_path)
            if not any(old in text for old, _ in legacy_patterns):
                continue
            if self._safe_replace_in_file(file_path, legacy_patterns, issue_id, "Standardize official logo references"):
                changed = True

        return changed

    def fix_lightweight_close_buttons(self, issue: Dict[str, Any]) -> bool:
        issue_id = issue.get("id", "unknown")
        return self.fix_lightweight_close_buttons_from_config(issue_id=issue_id)

    def fix_lightweight_close_buttons_from_config(self, issue_id: str = "lightweight-close-cleanup") -> bool:
        changed = False
        target_terms = self.config.get("lightweight_overlay_terms", ["Open Help", "AI Assistant", "popover", "dropdown", "helper"])
        close_patterns = self.config.get("close_button_patterns", [
            r"<button([^>]*)>\s*Close\s*</button>",
            r"<Button([^>]*)>\s*Close\s*</Button>",
        ])

        for file_path in self._find_candidate_files():
            text = read_text(file_path)
            if not any(term in text for term in target_terms):
                continue
            if not any(re.search(p, text) for p in close_patterns):
                continue

            if self._safe_replace_in_file(file_path, [(p, "") for p in close_patterns], issue_id, "Remove lightweight Close buttons", regex=True):
                changed = True

        return changed


# -----------------------------
# CLI
# -----------------------------

def default_config() -> Dict[str, Any]:
    return {
        "official_full_logo": "gulf-hisab-wordmark",
        "official_icon_logo": "icon",
        "search_extensions": [".tsx", ".ts", ".jsx", ".js", ".blade.php", ".php"],
        "internal_label_replacements": {
            "ZA": "",
            "VT": "",
            "WA": "",
            "RP": "",
            "IV": "",
            "MODULE": "",
            "Module": "",
        },
        "module_badge_patterns": [
            r">\s*MODULE\s*<",
            r">\s*Module\s*<",
            r">\s*ZA\s*<",
            r">\s*VT\s*<",
            r">\s*WA\s*<",
            r">\s*RP\s*<",
            r">\s*IV\s*<",
        ],
        "empty_cta_replacements": [
            (r"<button([^>]*)>\s*</button>", r"<button\1>Start Free Trial</button>"),
            (r"<a([^>]*)>\s*</a>", r"<a\1>Learn More</a>"),
        ],
        "known_404_nav_labels": [
            "User Workspace",
            "Admin Workspace",
            "Assistant Workspace",
            "Agent Workspace",
        ],
        "logo_reference_replacements": [
            ("/logo.svg", "/gulf-hisab-wordmark.svg"),
            ("logo.svg", "gulf-hisab-wordmark.svg"),
            ("icon-logo.svg", "icon.svg"),
            ("small-logo.svg", "icon.svg"),
            ("Gulf Hisab SVG Logo 1", "gulf-hisab-wordmark"),
            ("Gulf Hisabl SVG Logo 2", "icon"),
        ],
        "lightweight_overlay_terms": ["Open Help", "AI Assistant", "popover", "dropdown", "helper"],
        "close_button_patterns": [
            r"<button([^>]*)>\s*Close\s*</button>",
            r"<Button([^>]*)>\s*Close\s*</Button>",
        ],
    }


def find_latest_qa_report(project_root: Path) -> Optional[Path]:
    reports_dir = project_root / "qa_reports"
    if not reports_dir.exists():
        return None
    reports = sorted(reports_dir.glob("qa_report_*.json"), key=lambda p: p.stat().st_mtime, reverse=True)
    return reports[0] if reports else None


def report_to_dict(report: FixerReport) -> Dict[str, Any]:
    return {
        "generated_at": report.generated_at,
        "project_root": report.project_root,
        "qa_report_path": report.qa_report_path,
        "applied_count": report.applied_count,
        "skipped_count": report.skipped_count,
        "failed_count": report.failed_count,
        "actions": [asdict(a) for a in report.actions],
        "escalations": report.escalations,
    }


def main() -> None:
    project_root = Path(os.environ.get("GH_PROJECT_ROOT", ".")).resolve()
    config_path = Path(os.environ.get("GH_FIXER_CONFIG", "gh_fixer_config.json"))
    print(f"[Fixer] Loading config from {config_path}")

    if config_path.exists():
        config = json.loads(read_text(config_path))
    else:
        config = default_config()
        save_json(config_path, config)
        print(f"Created fixer config at {config_path}")

    qa_report_env = os.environ.get("GH_QA_REPORT")
    qa_report_path = Path(qa_report_env).resolve() if qa_report_env else find_latest_qa_report(project_root)

    if qa_report_path is None or not qa_report_path.exists():
        print("No QA report found. Run QA Inspector first.")
        sys.exit(1)

    print(f"[Fixer] Using QA report {qa_report_path}")

    engine = GulfHisabFixerEngine(project_root=project_root, qa_report_path=qa_report_path, config=config)
    report = engine.run()

    output_path = project_root / "qa_reports" / f"fixer_report_{datetime.utcnow().strftime('%Y%m%d_%H%M%S')}.json"
    save_json(output_path, report_to_dict(report))

    print(f"Fixer report generated: {output_path}")
    print(json.dumps({
        "applied_count": report.applied_count,
        "skipped_count": report.skipped_count,
        "failed_count": report.failed_count,
        "escalations": report.escalations[:10],
    }, indent=2, ensure_ascii=False))


if __name__ == "__main__":
    main()
